### ISSUE TITLE
Error: enabled: invalid property

### ISSUE THREAD

**Issue by alexlnkp** [szaffarano/wofi-power-menu#17]
Love the tool, but i stumbled upon a problem. Trying to customize the config of the wofi-power-menu leads to the error in the title. Here's my `.toml` file, mostly taken from the example in the README:
```toml
[wofi]
  extra_args = "--allow-markup --columns=1 --hide-scroll"

[menu.shutdown]
  title = "shutdown"

[menu.reboot]
  title = "reboot"

[menu.suspend]
  title = "suspend"
  enabled = "false"

[menu.hibernate]
  title = "hibernate"
  enabled = "false"

[menu.logout]
  title = "logout"

[menu.lock-screen]
    title = "lock"
    requires_confirmation = "false"
```

EDIT: also tried setting `disabled` to true, instead of `enabled` to false, same result. `Error: disabled: invalid property`
Trying to run with `wofi-power-menu -d suspend,hibernate` also doesn't work, menu items still appear.
