### ISSUE TITLE
Options confuse each other if some options are disabled

### ISSUE THREAD

**Issue by alexlnkp** [szaffarano/wofi-power-menu#21]
So here's my config:
```toml
[wofi]
  extra_args = "-H 900 --allow-markup --columns=1 --lines=8 --hide-scroll"

[menu.shutdown]
  title = "shutdown"

[menu.reboot]
  title = "reboot"

[menu.suspend]
  title = "suspend"
  enabled = "false"

[menu.hibernate]
  title = "hibernate"
  enabled = "false"

[menu.logout]
  title = "logout"
  cmd = "hyprctl dispatch exit"

[menu.lock-screen]
    title = "lock"
    requires_confirmation = "false"

```

If i select "logout" - i am asked for confirmation to **suspend** for some reason.
